{% set name = "hyperspyUI" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3dc190041247a9af5f25ca6cd45b32afc1889928fd735a77f70e7d48ee4d2c6

build:
  number: 0
  noarch: python
  entry_points:
    - hyperspyui = hyperspyui.__main__:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - __{{ target_os }}
    - python >=3.7
    - hyperspy-base
    - hyperspy-gui-traitsui
    - pyqode.python
    - autopep8
    - pep8
    - qtconsole
    - qtpy
    - ffmpeg
    - ipykernel >=5.2.0
  run_constrained:
    - menuinst >=1.4.17   # [win]

test:
  imports:
    - hyperspyui
    - hyperspyui.__main__

  # commands:
  #  - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'hyperspyui -h'
  #  - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'pytest --pyargs hyperspyui'

  # requires:
  #  - pytest
  #  - pytest-qt

app:
  entry: hyperspyui
  summary: HyperSpyUI
  type: desk

about:
  home: https://github.com/hyperspy/hyperspyUI
  license: GPL-3.0-or-later

  summary: "HyperSpyUI tries to bring a streamlined user interface to the powerful multi-dimensional analysis capabilities of HyperSpy. HyperSpy is an open source Python library which provides tools to facilitate data analysis of multidimensional datasets.\nHyperSpy aims at making it easy and natural to apply analytical\
    \ procedures that operate on an individual signal to multidimensional arrays, as well as providing easy access to analytical tools that exploit the multidimensionality of the dataset.\nWhile the UI tries to create a simple and intuitive interface to HyperSpy, it still retains the raw power of HyperSpy via the UI’s built\
    \ in IPython console, which runs on the same Python kernel as the UI. "
  license_file: COPYING.txt
  doc_url: http://hyperspy.org/hyperspyUI/
  dev_url: https://github.com/hyperspy/hyperspyUI

extra:
  recipe-maintainers:
    - vidartf
    - francisco-dlp
    - ericpre
