{% set name = "hyperspyUI" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyperspyui-{{ version }}.tar.gz
  sha256: 400dc0f7e53e7849811b8472e74978099503f0ed0ce5f0f77314729c7deb0f28

build:
  number: 1
  noarch: python
  script:
    - mkdir -p "{{ PREFIX }}/Menu"
    - sed "s/__PKG_VERSION__/{{ version }}/" "{{ RECIPE_DIR }}/menu.json" > "{{ PREFIX }}/Menu/hyperspyui_menu.json"
    - cp "{{ RECIPE_DIR }}/hyperspyui.icns" "{{ PREFIX }}/Menu/hyperspyui.icns"
    - cp "{{ RECIPE_DIR }}/hyperspyui.ico" "{{ PREFIX }}/Menu/hyperspyui.ico"
    - cp "{{ RECIPE_DIR }}/hyperspyui.png" "{{ PREFIX }}/Menu/hyperspyui.png"
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - hyperspyui = hyperspyui.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - exspy
    - hyperspy-base >=2.0
    - hyperspy-gui-traitsui >=2.0
    - pyqode.core >=4.0.10
    - pyqode.python >=4.0.2
    # Select pyqt binding since pyside6 is not supported
    # Add variant when pyside6 will be supported
    - pyqt
    - pyqtwebengine
    - pyflakes
    - autopep8
    - qtconsole-base >=5.2.0
    - qtpy
    - ffmpeg
    - ipykernel >=5.2.0
    - traitsui >=5.2.0
  run_constrained:
    - menuinst >=2

test:
  requires:
    - python {{ python_min }}
  imports:
    - hyperspyui
    - hyperspyui.__main__
  commands:
    # Check that the menu is installed
    - test -f ${CONDA_PREFIX}/Menu/hyperspyui_menu.json
    # Check we didn't forget any icons
    - test `ls ${CONDA_PREFIX}/Menu/hyperspyui.*  | wc -l` -eq 3
    # Check that the json file loads without error to catch json formatting issues
    - python -c "import json; json.load(open('${CONDA_PREFIX}/Menu/hyperspyui_menu.json'))"

  # commands:
  #  - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'hyperspyui -h'
  #  - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'pytest --pyargs hyperspyui'

  # requires:
  #  - pytest
  #  - pytest-qt

app:
  entry: hyperspyui
  summary: HyperSpyUI
  type: desk

about:
  home: https://github.com/hyperspy/hyperspyUI
  license: GPL-3.0-or-later

  summary: "HyperSpyUI tries to bring a streamlined user interface to the powerful multi-dimensional analysis capabilities of HyperSpy. HyperSpy is an open source Python library which provides tools to facilitate data analysis of multidimensional datasets.\nHyperSpy aims at making it easy and natural to apply analytical
    procedures that operate on an individual signal to multidimensional arrays, as well as providing easy access to analytical tools that exploit the multidimensionality of the dataset.\nWhile the UI tries to create a simple and intuitive interface to HyperSpy, it still retains the raw power of HyperSpy via the UI’s built
    in IPython console, which runs on the same Python kernel as the UI. "
  license_file: COPYING.txt
  doc_url: http://hyperspy.org/hyperspyUI/
  dev_url: https://github.com/hyperspy/hyperspyUI

extra:
  recipe-maintainers:
    - vidartf
    - francisco-dlp
    - ericpre
