travis:
  secure:
    BINSTAR_TOKEN: qJblbAbsopxWcVYzRotpOJECR5HcIzV6DFS13KIed8M/USp0qrsHRpypwD3ZNzxlywtKkFrqHfGbfUL5apSRlAz+e+eSQ/kXS0Ub3FQWUo3ibre4pToq6JDCfeoLnydE24TTCj6IaGfpTJ6JzG1hUsGSRQyt0hjTCuBYRUCwDMmf2o6XSfDYfXCoEx14rvdOV0liorvvc+VaTwaSWgF1u3lVFplFVIL+IqmfRwvVkFoCDbRhTjWgAEuLX1H7JYPJVf9bDZcy1R8ajYGsiKNflg3eLJkcMuRG2Gt9GUHtVpi1Ff0Hqdk1i8WepeFXAQ7aAsVfNNY1gXb6rnxPw20TSCVal3vO1RxI36atv2Lsz7qOUzD7sMydiGaiMRXMwi7xuJCN9R8G1sqFJwCTXq5MDrncE5KEbFSsiQEhtXS7hZnLJL6ncy3T5aWjLrGm6msP3N6IOmBMiSPJP8zC9dUHk/XVtvzUZTvisgaMQGGydY1r1RL2K4UmVEivk3yAh7MbkGsgUHaBiOgB8n1uBMy3XnHEmbvbX27BMFtcC0NK6v07mMIPASmChoTBfQ2xepvfOTjtaaInpMSTX37LEprHl0eg3fyMeg/vVX7Jhu8RdJuSzYSn2I5LztdTwColMtWMm9Cp11fsWPVT9GbKodLvUN8J1GRqxw8eEkugwKlwG6o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
